### ISSUE TITLE
Charm Incompatibility

### ISSUE THREAD

**Issue by BlueDemonTR** [NinjaPhenix/ExpandedStorage#13]
https://github.com/svenhjol/Charm/issues/576

**Comment by NinjaPhenix** [comment]
Seems like issue with charm, tested myself in AoF 4 with charm installed and it crashes with other barrels even charm's barrels.

**Comment by NinjaPhenix** [comment]
Fixed on charm's end, unfortunate issue but just a byproduct of fabric modding ethos.
