### ISSUE TITLE
Can't change inventory type

### ISSUE THREAD

**Issue by Atlas1124** [NinjaPhenix/ExpandedStorage#23]
Hey Ninja, I accidentally changed the inventory type (without even knowing how to open the UI) and now I can't change it back. I've tried Shift+e and Shift+Esc and neither work. What is the correct way to open the UI for that?

**Comment by NinjaPhenix** [comment]
Sorry forgot to mention it in the changelog but I changed the default keybind in the latest version to `shift` + `w`, it can be configured in the controls screen ( entry is prefixed with [ES] )

**Comment by NinjaPhenix** [comment]
Going to close this as there has been no further input.
