### ISSUE TITLE
[FEATURE REQUEST] Compatibility with Hey That's Mine

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [NinjaPhenix/ExpandedStorage#31]
Could you possibly make Expanded storage compatible with [Hey That's Mine](https://www.curseforge.com/minecraft/mc-mods/htm) mod? I asked the develpoer of HTM and they said that it's something you should do on your side because "[Hey That's Mine should be compatible with all containers. If it says it's not lockable, the mods hasn't implemented containers correctly and is extending regular BlockEntity instead of LockableContainerBlockEntity like all vanilla and modded containers should. Expanded Storage is also licensed under All Rights Reserved so I can't really do anything.](https://github.com/QuiltServerTools/HeyThatsMine/issues/14#issuecomment-880973369)"

**Comment by NinjaPhenix** [comment]
Doesn't look to bad, will see if I can get a build out tomorrow with support.

**Comment by NinjaPhenix** [comment]
Sorry for the delay, will take a look today.

**Comment by NinjaPhenix** [comment]
Working on 1 last thing before 7.0.0 is released so I'm going to hold off on releasing this until that is finished, shouldn't take more than a few days.

**Comment by Footage2-Amply-Pounce** [comment]
Closing this issue now, as I saw that you pushed the new update on CS, which makes your mod compatible with HTM. If I have any more problems with it, I'll reopen the issue.

Thank you!

**Comment by Footage2-Amply-Pounce** [comment]
Hmmm, I'm not sure why, but it's still not working together. Whenever I try to lock or unlock any container from Expanded Storage, HTM returns "Block not lockable". Tell me if there are any logs I could provide.

**Expanded Storage** 7.0.0+1.17.1
**HTM** 1.1.3

To reproduce, I placed a netherite chest down, typed "/htm set PUBLIC", hit enter, it promted me to left click on a chest I want to lock, I left clicked on the netherite chest and it returned "Block not lockable":

![2021-08-03_11 49 56](https://user-images.githubusercontent.com/86702831/127997845-da6558b1-5327-43ce-ab8b-8f862a47b65c.png)

Same thing with an iron chest, except I tried setting it to PRIVATE instead:

![2021-08-03_11 50 57](https://user-images.githubusercontent.com/86702831/127997919-44cada80-536e-4e6c-98ba-a1f18d0568ad.png)

Here's an example of how it works with a vanilla chest:

![2021-08-03_12 01 23](https://user-images.githubusercontent.com/86702831/127998178-33f105e6-728f-4526-a959-2ad8c42e1f00.png)

Here's an example of HTM working with a container from another mod, called Charm:

![2021-08-03_12 05 49](https://user-images.githubusercontent.com/86702831/127998272-b8e36504-ed4e-4d8b-994c-7a4d6f784be1.png)

The double old netherite chest you can see in the upper left corner also can't interact with HTM.

**Comment by NinjaPhenix** [comment]
IIRC 1.1.3 doesn't have compatibility so you will have to wait until 1.1.4 is released or build it from source.

**Comment by Footage2-Amply-Pounce** [comment]
Built it from source, and now it works, thanks again.
