### ISSUE TITLE
crash on load(1.14.4-expandedstorage-3.5.28+1.14.4)

### ISSUE THREAD

**Issue by SDUBZ** [NinjaPhenix/ExpandedStorage#31]
Fabric api: fabric-api-0.4.0+build.240-1.14
crash report 
http://puu.sh/EnWGV/8da0834bab.txt

**Comment by NinjaPhenix** [comment]
Hey you have both cursed chests and expanded storage installed can you try with just expanded storage

**Comment by SDUBZ** [comment]
okay @NinjaPhenix thanks for your help was doing it late at night brain derps but its loading still just gotta get the other mods fixed now 
Will close this issue
