### ISSUE TITLE
Conversion kits can be abused on minecraft:chest

### ISSUE THREAD

**Issue by TheKrowi** [NinjaPhenix/ExpandedStorage#33]
Clicking a double chest of minecraft:chest will only use 1 conversion kit when only 1 is in your inventory, will use 2 when more than 1 is in your inventory.

This way you can make chests of the higher tiers with half the resources.

**Comment by NinjaPhenix** [comment]
Thankyou for reporting this, got it fixed in dev and it will be release in the next update ( which hopefully should be soon ).

**Comment by NinjaPhenix** [comment]
Fixed in 3.6.29, 1.14.4 release will be comming out in ~5mins, 1.15.x release will be later today after I update other changes.
