### ISSUE TITLE
crash on load 1.15 pre1 (caused by bundled  creativebuttonmover)

### ISSUE THREAD

**Issue by SDUBZ** [NinjaPhenix/ExpandedStorage#34]
log:
http://puu.sh/EHp5q/d4dd692c40.log

Error loading class: net/fabricmc/fabric/impl/itemgroup/FabricCreativeGuiComponents$ItemGroupButtonWidget (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/itemgroup/FabricCreativeGuiComponents$ItemGroupButtonWidget)
[22:41:26] [main/WARN]: @Mixin#8976 target net.fabricmc.fabric.impl.itemgroup.FabricCreativeGuiComponents$ItemGroupButtonWidget was not found creativebuttonmover.mixins.client.json:FabricCreativeGuiComponentsMixin

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/NinjaPhenix/ExpandedStorage/files/3879667/latest.log)
expandedstorage-3.5.28+19w39a crashes on load aswell

**Comment by NinjaPhenix** [comment]
I'm still updating the mod to 1.15pre-1, I have not actually been updating the snapshot versions for a while now.

**Comment by SDUBZ** [comment]
just letting you know man :)

**Comment by NinjaPhenix** [comment]
Fixed in 3.6.29 for 1.15-pre1 which can be found [here](https://www.curseforge.com/minecraft/mc-mods/expanded-storage/files/2831577).
