### ISSUE TITLE
Crash on load 1.15-pre6

### ISSUE THREAD

**Issue by IvanKulagin** [NinjaPhenix/ExpandedStorage#36]
Crash on load on 1.15-pre6 using last version of the mod (expandedstorage-3.8.33+1.15-pre6)

[crash-2019-12-08_16.04.50-client.txt](https://github.com/NinjaPhenix/ExpandedStorage/files/3936245/crash-2019-12-08_16.04.50-client.txt)

**Comment by Gbergz** [comment]
Same here! I downgraded to "[expandedstorage-3.7.32+1.15-pre6.jar](https://www.curseforge.com/minecraft/mc-mods/expanded-storage/files/2837839)" and it loaded fine. A solution until it's fixed! :)

**Comment by NinjaPhenix** [comment]
Thanks for creating an issue, I already started on the next update (and forgot to save the source code of that build) but I've fixed the issue in dev. That version only added towelette support (which isn't officially out on curseforge yet). I'll have a new build out today or tomorrow Likely versioned 3.9.34

**Comment by NinjaPhenix** [comment]
Sorry for the bugged builds recently, theres a 1.15 build on curseforge now (4.9.35) which functions properly.
