### ISSUE TITLE
Items do not Save on Server Restart

### ISSUE THREAD

**Issue by SteveKnowless** [NinjaPhenix/ExpandedStorage#37]
Minecraft: 1.15
Fabric Loader 0.7.2 Build 174
Fabric API 0.4.24 Build 279
ExpandedStorage 3.8.33 pre6

Once Items are put into an ExpandedSotrage Chest and if the Server is restarted all items in that chest are lost. It does not matter if it is a regular ExpandedSotrage Chest or Old ExpandedSotrage Chest.

**Comment by NinjaPhenix** [comment]
Sorry, I had this reported before by another user and thought I had deleted all the builds on curseforge that was deleting items. For some reason curseforge isn't letting me delete this version either. But I'll have a fixed version out later today after doing a bunch of testing, sadly this does mean your items are gone.

**Comment by NinjaPhenix** [comment]
Fixed in latest version on curseforge 4.9.35, I'm very sorry about this bug.
