### ISSUE TITLE
Crashing witrh Iris and Sodium installed

### ISSUE THREAD

**Issue by Sinogard** [NinjaPhenix/ExpandedStorage#38]
Crash report here https://pastebin.pl/view/e94055b4

**Comment by NinjaPhenix** [comment]
Looks like a mixin conflict between coloured lights and sodium, I'd give installing indium a shot as that may fix the issue.

You can get indium at:
GitHub: https://github.com/comp500/Indium
Modrinth: https://modrinth.com/mod/indium

**Comment by Sinogard** [comment]
Sodium and Iris do not like eachother at the moment. I removed Sodium and it started working. Sorry for wasting your time but thanks for the help.
