### ISSUE TITLE
[1.15.1-Forge] Error Loading Mods

### ISSUE THREAD

**Issue by Gbergz** [NinjaPhenix/ExpandedStorage#40]
Mod can't load on Client getting "Error loading mod" error.

**Logs: [https://gist.github.com/Gbergz/37eb94f0174e2937cc3033bcf09bfeb8](https://gist.github.com/Gbergz/37eb94f0174e2937cc3033bcf09bfeb8)
**Screenshot**:  
![cursedchestserror](https://user-images.githubusercontent.com/26634554/72670310-6ed31f00-3a3c-11ea-9c12-279d7c9c8d32.PNG)

**MC Version**: 1.15.1
**Forge Version**: 30.0.41
**Mod-Version**: 1.1.2+1.15.1

Any ideas? :)

**Comment by MrCrayfish** [comment]
It's because the method signature of ClientRegistry#bindTileEntityRenderer is different in newer versions of Forge. Hopefully they fix soon!

**Comment by NinjaPhenix** [comment]
Thanks for letting me know, spent ages trying to get my item rendering to work as well as block rendering so I just published it on the forge build I first started the port on, 30.0.7 I believe. I'll get an updated build out soon.

**Comment by NinjaPhenix** [comment]
Fixed build can be found here, also found a crash on dedicated servers when opening a chest which is now also fixed: https://www.curseforge.com/minecraft/mc-mods/expanded-storage/files/2863717.
