### ISSUE TITLE
1.16.5 Found a serious problem 

### ISSUE THREAD

**Issue by Dr-WeiAL** [NinjaPhenix/ExpandedStorage#41]
When using Sophisticated Backpacks, there was a bug when interacting with the mod. The container of the tested vanilla chest and other mods did not have this problem. 

When stack upgrade tier is used when deposit is used, and there are more than 64 items in the backpack, the items will be lost after putting in the chest 

I used machine translation, please see the picture if the expression is not clear 

![image](https://user-images.githubusercontent.com/47446553/129094015-bc1b02ec-7a0c-4567-9980-a17c2233c468.png)
![image](https://user-images.githubusercontent.com/47446553/129095054-6260b478-e885-4d6b-9547-1e4a2cb0313e.png)
![image](https://user-images.githubusercontent.com/47446553/129094087-ca0f020d-a53e-4287-bbca-b90abbcd0fed.png)

**Comment by NinjaPhenix** [comment]
Sorry for delay in response will take a look into fixing this now.

**Comment by Dr-WeiAL** [comment]
> Sorry for delay in response will take a look into fixing this now.

Thanks for your hard work

**Comment by NinjaPhenix** [comment]
Fixed in 7.0.1 thankyou for reporting, https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge/files/3431510
