### ISSUE TITLE
Scroll doesn't seems to work

### ISSUE THREAD

**Issue by dureiken** [NinjaPhenix/ExpandedStorage#42]
Hi

thanks for your work :)

the scroll doesn't seem to work on Forge and 1.15.1. Iron, gold and Diamond chests have 9*6 items to stock.

**Comment by meaqua11** [comment]
Me too.....

**Comment by NinjaPhenix** [comment]
Just realised some code that was working whilst developing didn't work in production, I've released a fix in version 1.1.4 for 1.15.1 however this version will not work with forge versions newer than 30.0.43

https://www.curseforge.com/minecraft/mc-mods/expanded-storage/files/2867105

**Comment by meaqua11** [comment]
Thank you for your hard work.

**Comment by dureiken** [comment]
Thanks for the work !

why not after forge 43 ?

**Comment by NinjaPhenix** [comment]
There were changes to one of the render methods I used so my mod would just crash, I released a new version thats compatable with forge versions 50+ though.

**Comment by dureiken** [comment]
ok :) don't hesitate to keep working :p thanks for that mod

is that possible to add a sorting function you think ?

**Comment by NinjaPhenix** [comment]
Well it would be possible to add, how easy/quickly I can add it though I'm not sure.
I will look into adding some sorting buttons in the future.
