### ISSUE TITLE
Feature Request: Config option to enable keyboard input upon opening chest

### ISSUE THREAD

**Issue by Trnrr** [NinjaPhenix/ExpandedStorage#43]
Hello I would like to request a feature if possible. When you open any chest that includes the search feature (gold and up I believe), it would be nice if the cursor was ready for text input. A lot of the times I open the chest looking for a specific item and have to click the text box each time. It would be a quality if life improvement if the chest was ready for text input on opening. If someone didn't want to type anything then they could just click the item as usual. Thank you

**Comment by NinjaPhenix** [comment]
Easy enough todo, I'll have an update out later which includes this.

**Comment by NinjaPhenix** [comment]
Updated for forge, fabric will have to wait till later.

**Comment by Trnrr** [comment]
Ok sweet. Can't wait till fabric update is released 😄

**Comment by NinjaPhenix** [comment]
I'll get started on it shortly

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Trnrr** [comment]
No problem, take your time. Just glad that it will be coming.

**Comment by NinjaPhenix** [comment]
It's actually just been finished, just need to upload it.

**Comment by NinjaPhenix** [comment]
Version for 1.15.2 is out, update for 20w06a will be out tomorrow with netherite chests.

**Comment by Trnrr** [comment]
Ok no problem.

**Comment by NinjaPhenix** [comment]
Oh well I didn't see the config option part but its now included in version for 20w06a: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/2881218

**Comment by Trnrr** [comment]
Just downloaded the version of curse (4.11.37) and it doesn't auto focus. I also tried it on a test pack with just that mod, dataloader and fabric api and it didnt work

**Comment by NinjaPhenix** [comment]
Huh will check on that now...

**Comment by Trnrr** [comment]
If they won't accept the file I would appreciate if you could send it to me on discord. My id is Turner#0001

**Comment by NinjaPhenix** [comment]
Fixed jar and is now on curseforge: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/2882585
