### ISSUE TITLE
[Help] Documentation on how to build the project.

### ISSUE THREAD

**Issue by shinjitumala** [NinjaPhenix/ExpandedStorage#71]
Hello. I was trying to do some hacking with your code but I am having trouble building this project.

I was able to build the `container-library` but not this one. It complains about not being able to find `container-library`.

Any hints on how to build this mod successfully would be very appreciated.

<details>
<summary>Output of gradle</summary>

```
ExpandedStorage $ ./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fabric'.
> Could not resolve all dependencies for configuration ':fabric:modImplementation'.
   > Could not find ninjaphenix:container_library:1.2.5+1.17.1.
     Searched in the following locations:
       - file:/home/<redacted>/github/ExpandedStorage/.gradle/loom-cache/remapped_mods/ninjaphenix/container_library/1.2.5+1.17.1/container_library-1.2.5+1.17.1.pom
       - https://maven.fabricmc.net/ninjaphenix/container_library/1.2.5+1.17.1/container_library-1.2.5+1.17.1.pom
       - https://libraries.minecraft.net/ninjaphenix/container_library/1.2.5+1.17.1/container_library-1.2.5+1.17.1.pom
       - https://repo.maven.apache.org/maven2/ninjaphenix/container_library/1.2.5+1.17.1/container_library-1.2.5+1.17.1.pom
       - file:/home/<redacted>/.gradle/caches/fabric-loom/1.2.5+1.17.1/container_library-fabric.jar
       - file:/home/<redacted>/github/ExpandedStorage/.gradle/loom-cache/1.2.5+1.17.1/container_library-fabric.jar
       - https://oss.sonatype.org/content/repositories/snapshots/ninjaphenix/container_library/1.2.5+1.17.1/container_library-1.2.5+1.17.1.pom
       - file:/home/<redacted>/.m2/repository/ninjaphenix/container_library/1.2.5+1.17.1/container_library-1.2.5+1.17.1.pom
     Required by:
         project :fabric

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

</details>

**Comment by NinjaPhenix** [comment]
You need to clone and publish this project to maven local before trying to build expanded storage currently: https://github.com/NinjaPhenix/container-library, it can be published to maven local using `./gradlew :publishToMavenLocal`

Had been using jitpack before but it is not working as well as I hoped but I will get my own maven server at some point in the future to not require users to do this anymore.

**Comment by shinjitumala** [comment]
Thank you. I was able to successfully build this mod with those instructions.

**Comment by NinjaPhenix** [comment]
Will add them to the readme for the 7.3 branches which will eventually be merged into the main release branches...

**Comment by NinjaPhenix** [comment]
No longer an issue as container library is now pulled from curseforge's "maven" though I should probably switch this to modrinth' s maven as that is officially supported.
