### ISSUE TITLE
[BUG][ISSUE] REI Incompatibility - Fabric

### ISSUE THREAD

**Issue by Mitchell-Jones-Comf** [NinjaPhenix/ExpandedStorage#9]
Expanded Storage for 1.17 throws error's and stops REI from creating its plugin forcing Minecraft to exit.

![image](https://user-images.githubusercontent.com/56074358/122040889-45085e00-cdd0-11eb-99dc-f08dd4b57eaf.png)

[latest.log](https://github.com/NinjaPhenix/ExpandedStorage/files/6655012/latest.log)

**Comment by NinjaPhenix** [comment]
Please use the latest alpha version for 1.17 https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3350196

**Comment by Mitchell-Jones-Comf** [comment]
Perfect, didn't realise there were Alpha versions.

Thank you
